### ISSUE TITLE
Dizilla ve dizipal sorunu

### ISSUE THREAD

**Issue by turbetfur** [keyiflerolsun/Kekik-cloudstream#101]
Dizilla da bazı önemli diziler örneğin From adlı dizi KekikAkademi eklentisinde arayınca çıkıyor fakat içerik oynamıyor. Dizipal de yine örneğin from adlı dizi kendi sitesinde aratınca çıkıyor ve oynuyor fakat ilginç bir şekilde KekikAkademi de diziplade aratınca çıkmıyor. Kısacası bazı önemli tanınmış dizilere bu önlemi almışlar artık. From adlı diziyi örnek verdim çoğu beğenilen diziyi böyle yapmışlar.

**Comment by keyiflerolsun** [comment]
#7
