### ISSUE TITLE
Rectv dizi ve film bölümü 

### ISSUE THREAD

**Issue by turbetfur** [keyiflerolsun/Kekik-cloudstream#102]
Eklentide ki telif hakkı olan dizi veya filmler hiç bir kaynakta oynamıyor. Bir tek rect tv nin kendi programında var. Bu işi bilen bir arkadaş rectv nin sadece film ve dizi bölümünü tekrar ekleyemez mi?

**Comment by keyiflerolsun** [comment]
#7 içerisine yazın lütfen
