### ISSUE TITLE
Dizipal

### ISSUE THREAD

**Issue by VK5816** [keyiflerolsun/Kekik-cloudstream#112]
Dizipal hiçbir içeriğe ulaşamıyorum uzun zamandırda bi sorun var

**Comment by OZGUNNx** [comment]
Evet dizipal orijinal olan hangisi bilmiyorum ama şuan aktif bir dizipal var rica etsek onu ekyebilir misiniz ??

**Comment by keyiflerolsun** [comment]
#7
