### ISSUE TITLE
Prime Video Plugin Refinement

### ISSUE THREAD

**Issue by Politecoder** [keyiflerolsun/Kekik-cloudstream#115]
https://github.com/user-attachments/assets/634dc2cd-57de-46c0-9832-794bf9884451

As you can see in the above video some series are not working, will be great if you fix it.

**Comment by Politecoder** [comment]
![Screenshot_2024-11-04-17-55-57-363](https://github.com/user-attachments/assets/51f48f76-f0cd-4a0c-bfce-ab8455144512)
Also please add movies recommendation too on the homepage as it just shows the series on it..

**Comment by keyiflerolsun** [comment]
https://github.com/user-attachments/assets/d3e78594-5d8d-4d48-bd79-509f3cd9a71c
