### ISSUE TITLE
Canlı TV için Kaynak Önerisi

### ISSUE THREAD

**Issue by ramazansancar** [keyiflerolsun/Kekik-cloudstream#27]
Merhaba,
Canlı TV için sürekli olarak güncellenen kaynak önerim olacak.

- https://iptv-org.github.io/iptv/languages/tur.m3u
- https://iptv-org.github.io/iptv/countries/tr.m3u

Repo: https://github.com/iptv-org/database

**Comment by keyiflerolsun** [comment]
❔ _Kendi IPTV (M3U) Listenizi içe Aktarabileceğinizi Biliyor Muydunuz?_ »» **https://t.me/KekikAkademi/1756**

**Comment by ramazansancar** [comment]
> ❔ _Kendi IPTV (M3U) Listenizi içe Aktarabileceğinizi Biliyor Muydunuz?_ »» **https://t.me/s/KekikAkademi/1756**

Teşekkürler bundan haberim yoktu. Bilgi için teşekkürler
