### ISSUE TITLE
Mailru extractor doesnt work

### ISSUE THREAD

**Issue by aymanbest** [keyiflerolsun/Kekik-cloudstream#37]
tested on this :
https://my.mail.ru/video/embed/7496205347414082782

**Comment by keyiflerolsun** [comment]
it's work

![Screenshot_2024-01-11-21-40-23-151_com lagradost cloudstream3 prerelease](https://github.com/keyiflerolsun/Kekik-cloudstream/assets/57468649/30f8563f-20d7-4557-a166-337b47898501)
