### ISSUE TITLE
dizilla calışmıyor

### ISSUE THREAD

**Issue by testermania** [keyiflerolsun/Kekik-cloudstream#70]
contentx.me adresi dns hatası veriyor bu yüzden dizilla çalışmıyor. fullhdfilmizlesene de hiç yüksek kaliteli açmıyor hep düşük kalite.

**Comment by keyiflerolsun** [comment]
https://github.com/keyiflerolsun/Kekik-cloudstream/commit/71b548e8af4b468f5c57f27cd3dc1892c6250bdc sonrasında dizilla sorunu çözülmüştür

**Comment by keyiflerolsun** [comment]
kaliteyi parçalar sekmesinden kendiniz seçebiliyorsunuz; 
![image](https://github.com/keyiflerolsun/Kekik-cloudstream/assets/57468649/34e2a57c-810d-4fa5-b04b-ec8ea319a038)

**Comment by testermania** [comment]
kalite sekmesinde onların hiç biri cıkmıyor, dizilla da değişen bir şey yok, html kodları uyumlu olmadığı için kategoriler posterler yuklenmiyor. hdfilmcehennemi de tema değişmiş o da aynı durumuda şu an.

**Comment by keyiflerolsun** [comment]
> kalite sekmesinde onların hiç biri cıkmıyor, dizilla da da değişen bir şey yok, html kodları uyumlu olmadığı için dublaj kategorisi hariç diğer kategoriler yüklenmiyor. hdfilmcehennemi de tema değişmiş onda sadece kategoriler görünüyor.

[pre-relase](https://github.com/recloudstream/cloudstream/releases/tag/pre-release) kullanmanızı tavsiye ederim. hdfilmcehennemi güncellendi..

**Comment by testermania** [comment]
linteki pre-release yükledim, olumsuz aynı sorunlar devam ediyor.

**Comment by testermania** [comment]
pre-release denedim hdfilmcehennemi düzelmiş, dizilla aynı halen dublaj kısmı var sadece altta kategoriler sadece isim olarak var basıyorsun acılmıyor.

**Comment by testermania** [comment]
pre-release denedim hdfilmcehennemi düzelmiş, dizilla aynı, halen dublaj kısmı acılıyor. altta kategoriler sadece isim olarak görünüyor.

**Comment by keyiflerolsun** [comment]
dizillayı tekrar kontrol eder misiniz?

FullHDFilmizlesene de 4k destekli film örneğini doğrudan link ile sağlar mısınız kontrol edeyim..

**Comment by testermania** [comment]
dizilla tamam. 4k destekli link te bu fullhdfilmizlesene.de/film/transformers-3-ayin-karanlik-yuzu/

**Comment by keyiflerolsun** [comment]
dizilla için kategori sayfalama fonksiyonunu yazmadım. arama yaparak dilediğiniz içeriğe erişebilirsiniz.

FullHDFilmizlesene de de sorun gözükmüyor 
![Screenshot_2024-06-21-22-39-30-596_com lagradost cloudstream3 prerelease](https://github.com/keyiflerolsun/Kekik-cloudstream/assets/57468649/3e3e2a93-5470-49fa-9a91-8ae9e2b0dcd5)

**Comment by testermania** [comment]
bende de bu şekilde

kaynak kısmı
https://ibb.co/16LNgXP

parçalar
https://ibb.co/ww2jQrN

**Comment by testermania** [comment]
![Screenshot-20240621-224806](https://github.com/keyiflerolsun/Kekik-cloudstream/assets/61498468/ba7d4997-1cc9-40f7-a85b-baa82abde789)
![Screenshot-20240621-224819](https://github.com/keyiflerolsun/Kekik-cloudstream/assets/61498468/812cae3f-aea4-4273-8078-9226778bf026)

**Comment by testermania** [comment]
4.3.0 a geçtim yeni sürümlerde eklentilerde hata veriyor.

aşağıdaki film neden açmıyor tarayıcıdan açınca fast gösteriyor açılıyor. uygulamada bağlantı bulunamadı diyor. ayrıca düşük çözünürlük sorunu olanların hepsi sanırım rapidvid olanlar.
https://www.fullhdfilmizlesene.de/film/john-carter-iki-dunya-arasinda/

**Comment by keyiflerolsun** [comment]
> 4.3.0 a geçtim yeni sürümlerde eklentilerde hata veriyor.
> 
> aşağıdaki film neden açmıyor tarayıcıdan açınca fast gösteriyor açılıyor. uygulamada bağlantı bulunamadı diyor. ayrıca düşük çözünürlük sorunu olanların hepsi sanırım rapidvid olanlar. https://www.fullhdfilmizlesene.de/film/john-carter-iki-dunya-arasinda/

Main Repo PR bekliyor;

https://github.com/recloudstream/cloudstream/pull/1184
