### ISSUE TITLE
Stremio

### ISSUE THREAD

**Issue by BardaktakiAdam** [keyiflerolsun/Kekik-cloudstream#71]
Merhabalar öncelikle elinize sağlık gerçekten muazzam çalışıyor cloudstream de fakat aynı bu şekilde bu eklentiyi Stremio'ya da kurmak mümkün müdür acaba? Teşekkürler

**Comment by keyiflerolsun** [comment]
Merhabalar,

Streamio eklentilerini Cloudstream'de kullanmak mümkün; https://recloudstream.github.io/csdocs/integrations/stemiorelated

fakat tersi durumu Streamio tarafına sormanız gerekli 😊
