### ISSUE TITLE
dizipal sorunu

### ISSUE THREAD

**Issue by yusiqo** [keyiflerolsun/Kekik-cloudstream#72]
eklediğiniz dizipal domaininde cloudflare açılıyor sıklıkla o yüzden calismiyor uygulama. dizipalin ek domainlerinide ekleyin

**Comment by keyiflerolsun** [comment]
sorun gözükmemektedir.. 

![Screenshot_2024-07-06-23-20-00-617_com lagradost cloudstream3 prerelease](https://github.com/keyiflerolsun/Kekik-cloudstream/assets/57468649/db2d1110-bfc3-4c33-b40b-a96e37a66e15)

**Comment by yusiqo** [comment]
> sorun gözükmemektedir.. 
> 
> ![Screenshot_2024-07-06-23-20-00-617_com lagradost cloudstream3 prerelease](https://github.com/keyiflerolsun/Kekik-cloudstream/assets/57468649/db2d1110-bfc3-4c33-b40b-a96e37a66e15)

Hocam bilmiyorum Azerbaycanliyim ulke ip sinden dolayıda olabilir. yinede dizipalın ek domaininde olan siteyide ekleye bilirmisiniz eğer zahmet değilse.
