### ISSUE TITLE
Turkish series with urdu subtitles for Pakistani audience 

### ISSUE THREAD

**Issue by AsfandYar1211** [keyiflerolsun/Kekik-cloudstream#74]
Kindly Add some resources for Pakistani/ urdu audience as there is no extension available yet 
https://makkitv.com/
https://superurdu.com/
https://play.niazitv.pk/
https://turkceurdu.com/
https://play.qayadat.org/
https://www.urdubolo.pk/
https://kayifamily.com/ ( eng)
https://kayifamilytv.pk/

**Comment by keyiflerolsun** [comment]
Hello,

Thank you for your interest. However, this repository exclusively contains extensions for the Turkish language. Currently, there are no plans to develop extensions for Pakistani or Urdu-speaking audiences.

Thank you for your understanding.
