### ISSUE TITLE
HDFilmCehennemi oynatma linkleri bulunamadı hatası

### ISSUE THREAD

**Issue by atorata** [keyiflerolsun/Kekik-cloudstream#78]
Plugin film bilgilerini sorunsuz getiriyor ancak sitede film kaynağı olarak HLS yapısına geçtiğinden linkleri bulamıyor. 

https://www.hdfilmcehennemi.sh/kingdom-of-the-planet-of-the-apes-3/ için konuşursak 

https://hdfilmcehennemi.mobi/video/embed/yc2TjoDWZAH/ah/ url ine post isteği sonrasında 

https://srv9.servercdn1234.fun/hls/kingdomoftheplanetoftheapes20241080pwebriptrdubforcedmp4-yc2TjoDWZAH.mp4/txt/master.txt adında bir playlist indiriyor.

Player aşağıdaki linklerden jpg uzantılı görünen aslında muhtemelen mp4 içeriği olan parçaları birleştirerek videoyu oluşturuyor.

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:6
#EXTINF:5.208000,
https://srv9.servercdn804.fun/hls/kingdomoftheplanetoftheapes20241080pwebriptrdubforcedmp4-yc2TjoDWZAH.mp4/image000.jpg
#EXTINF:5.208978,
https://srv9.servercdn804.fun/hls/kingdomoftheplanetoftheapes20241080pwebriptrdubforcedmp4-yc2TjoDWZAH.mp4/image001.jpg
#EXTINF:5.208011,
https://srv9.servercdn804.fun/hls/kingdomoftheplanetoftheapes20241080pwebriptrdubforcedmp4-yc2TjoDWZAH.mp4/image002.jpg
#EXTINF:5.208000,
https://srv9.servercdn804.fun/hls/kingdomoftheplanetoftheapes20241080pwebriptrdubforcedmp4-yc2TjoDWZAH.mp4/image003.jpg

**Comment by keyiflerolsun** [comment]
#7
