### ISSUE TITLE
REC TV Android TV oynatmıyor 

### ISSUE THREAD

**Issue by almrkc** [keyiflerolsun/Kekik-cloudstream#82]
Cep telefonuda gayet normal ve güzel oynatıyor. Android Tv'de, BAD ERROR 2001 diye hata var. Sadece Canlı yayın değil. Bütün iceriklar aynı.

**Comment by keyiflerolsun** [comment]
#7

**Comment by almrkc** [comment]
Çözüldü! ANDROID TV'DE dns over TLS ayarı vardı. Bunu değiştirdim. Saygılar.

**Comment by testermania** [comment]
değiştirdim derken açtınız mı kapadınız mı. hangi dns ye aldınız.

**Comment by almrkc** [comment]
Önceden kullandığım, reklam engellemek için olan https://**dns.nextdns**.io adresini(dns), adb üzerinden kapattım. Şuan sadece Cloudstream içinde olana Cloudflare DNS ile bağlanıyorum, sorunsuz.
