### ISSUE TITLE
Kaynak Önerisi

### ISSUE THREAD

**Issue by apkbir** [keyiflerolsun/Kekik-cloudstream#9]
- [ ] Filmmodu
- [ ] 4kfilm izle

sitelerini ekleyebilir misiniz ?

---

- [ ] roketdizi.co
- [ ] seriesaz.com
- [x] jetfilmizle.cx
- [ ] ddizi.pro
- [ ] webteizle2.com
- [ ] Yabancıdizi.pro
- [ ] dizimax.club
- [ ] sezonlukdizi

**Comment by keyiflerolsun** [comment]
- [ ] roketdizi.co
- [ ] seriesaz.com
- [ ] jetfilmizle.cx

**Comment by xcbly** [comment]
webteizle2.com

**Comment by JustSadY** [comment]
Yabancıdizi.pro ekleyebilirmisiniz

**Comment by digitvadmin** [comment]
dizimax.club sitesini ekleyebilir misiniz ? Vip alan var ama üyelik olmadan verileri çekilebilir mi bilemiyorum tabi.

**Comment by Vhkjr** [comment]
sezonlukdiziyi ekliyebilirnisin ordaki icerikler baska yerde olmuyor ozgun bir sistemi var playerda vidmoly onceden yaptigin icin cok ugrastirmaz

**Comment by keyiflerolsun** [comment]
#1 ile birleştirildi

**Comment by akbaba79** [comment]
4k film izle eklense çok güzel olur.
