### ISSUE TITLE
Rec tv içerik oynatma hatası

### ISSUE THREAD

**Issue by fsozkan** [keyiflerolsun/Kekik-cloudstream#90]
İçerik oynatma istediğim de rec tv ekteki hatayı veriyor.  
![Uploading IMG_20240822_114619.jpg…]()

**Comment by fsozkan** [comment]
![Uploading IMG_20240822_114619.jpg…]()

**Comment by keyiflerolsun** [comment]
#7

**Comment by lavara123** [comment]
@keyiflerolsun Rectv çalışmıyor
