### ISSUE TITLE
Eski dizipal domain kullanımı

### ISSUE THREAD

**Issue by ahmetcanisik** [keyiflerolsun/Kekik-cloudstream#91]
Güncel dizipal domain adresi <https://dizipal738.com> olmuştur. Dilerseniz kendi api linkimden de güncel adresi takip edebilirsiniz. <https://raw.githubusercontent.com/dizipaltv/api/main/dizipal.json>

**Comment by keyiflerolsun** [comment]
Merhabalar, hali hazırda 738 kullanılıyor zaten.

mevcut düzende github actions ile kendimiz kontrol sağlıyoruz.

**Comment by ahmetcanisik** [comment]
Ben sadece bu satırı kastetmiştim diğer kodları incelemedim. işte burada hala 737 kullanılıyor:

https://github.com/keyiflerolsun/Kekik-cloudstream/blob/27c8c100d94b91f509e55bdb44801201893ed5e4/DiziPal/src/main/kotlin/com/keyiflerolsun/bakalim.py#L10
